
stages:
  - build
  - test
  - push

variables:
  REGISTRY_IMAGE: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}"

# Build Job
build:
  stage: build
  script:
    - docker build -t $REGISTRY_IMAGE --build-arg NODE_ENV=production --build-arg PORT=3000 .
  only:
    - main

# Test Job
test:
  stage: test
  image: node:14
  script:
    - npm install
    - npm test
  only:
    - main

# Push Job
push:
  stage: push
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push $REGISTRY_IMAGE
  only:
    - main
