stages:
  - build
  - test
  - package
  - deploy
  - notify

variables:
  DOCKER_IMAGE: "your-docker-registry/web-app"
  HELM_CHART_DIR: "./charts/web-app"
  KUBE_CONTEXT: "your-k8s-cluster"

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHA .
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA
  only:
    - main

test:
  stage: test
  script:
    - echo "Running tests..."
    - npm install
    - npm test
  only:
    - main

package_helm:
  stage: package
  script:
    - helm lint $HELM_CHART_DIR
    - helm package $HELM_CHART_DIR
  artifacts:
    paths:
      - "*.tgz"
  only:
    - main

deploy:
  stage: deploy
  script:
    - helm upgrade --install web-app $HELM_CHART_DIR --namespace dev --set image.tag=$CI_COMMIT_SHA
  only:
    - main

notify:
  stage: notify
  script:
    - echo "Deployment Successful!"
  only:
    - main
